package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Station;
import greendao.Position;

import greendao.StationDao;
import greendao.PositionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stationDaoConfig;
    private final DaoConfig positionDaoConfig;

    private final StationDao stationDao;
    private final PositionDao positionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stationDaoConfig = daoConfigMap.get(StationDao.class).clone();
        stationDaoConfig.initIdentityScope(type);

        positionDaoConfig = daoConfigMap.get(PositionDao.class).clone();
        positionDaoConfig.initIdentityScope(type);

        stationDao = new StationDao(stationDaoConfig, this);
        positionDao = new PositionDao(positionDaoConfig, this);

        registerDao(Station.class, stationDao);
        registerDao(Position.class, positionDao);
    }
    
    public void clear() {
        stationDaoConfig.getIdentityScope().clear();
        positionDaoConfig.getIdentityScope().clear();
    }

    public StationDao getStationDao() {
        return stationDao;
    }

    public PositionDao getPositionDao() {
        return positionDao;
    }

}
